steps:
  - command: "apk add docker"
    label: "Install docker"
    agents:
      - "queue=mpto-dpd-base-agent"

  - command: "apk add --update nodejs npm"
    label: "Install npm"
    agents:
      - "queue=mpto-dpd-base-agent"

  - command: "npm install\nnpm test"
    label: "Test"
    agents:
      - "queue=mpto-dpd-base-agent"

  - command: "docker build -f Dockerfile -t quay.io/michelle_peralbo/nodeapptest . \ndocker images"
    label: "Build image"
    agents:
      - "queue=mpto-dpd-base-agent"
  - command: "docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD} quay.io \ndocker push quay.io/michelle_peralbo/nodeapptest"
    label: "Push image to quay"
    agents:
      - "queue=mpto-dpd-base-agent"
