apiVersion: v1
kind: Secret
metadata:
  name: db-creds
type: Opaque # (otros tipos) https://stackoverflow.com/a/54552984/607502
stringData: #K8s codifica en base64
  user: 'root'
  password: 'mypassword'
  host: 'mydb.example.com'