apiVersion: v1
kind: Service
metadata:
  name: mongoservice
  namespace: test
spec: 
  selector:
    app: mongo-example
  ports:
    - protocol: TCP
      port: 27017 
      targetPort: 27017
  type: NodePort  
